### ISSUE TITLE
Running `docker build` fails

### ISSUE THREAD

**Issue by daniellivingston** [ecoon/watershed-workflow#2]
Running the command:

```sh
docker build -t watershed_workflow .
```

throws the following error:

```
/opt/conda/compiler_compat/ld: cannot find -lboost_python36
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
The command '/bin/sh -c git clone https://github.com/ecoon/meshpy.git &&     cd meshpy &&     ./configure.py --python-exe=${ANACONDA_DIR}/bin/python --boost-inc-dir=${ANACONDA_DIR}/include  --boost-lib-dir=${ANACONDA_DIR}/lib --boost-python-libname=boost_python36  --disable-static --enable-shared &&     python setup.py build &&     python setup.py install &&     cd' returned a non-zero code: 1
```

On Docker Desktop 2.3.0.4, macOS 10.14.6, commit 463d6d75a21362c8e446129f241ce6e95dc414a0.

The full log is available here: [docker_errors.log](https://github.com/ecoon/watershed-workflow/files/5099697/docker_errors.log)

**Comment by ecoon** [comment]
Thanks Daniel, will take a look.  I haven't actually been using the docker container much lately, so it probably is out of date.  If you can, try the anaconda install command instead.

**Comment by ecoon** [comment]
Fixed, see the documentation for how to get docker builds now from Dockerhub (or build them locally if you prefer).
